FROM python:3.9-alpine

RUN apk update && apk add --no-cache build-base musl-dev libffi-dev
#todo cython
RUN pip install pyinstaller 

RUN addgroup -S compgroup
RUN adduser -S compuser -G compgroup
USER compuser

WORKDIR /app
COPY comp.sh .
RUN mkdir /tmp/out
RUN mkdir /tmp/in


ENTRYPOINT ["./comp.sh"]
