FROM alpine:3.21

WORKDIR /app



RUN apk add --no-cache python3 py3-pydantic py3-psutil
RUN addgroup -S execgroup
RUN adduser -S execuser -G execgroup

USER execuser

RUN mkdir /tmp/in
RUN mkdir /tmp/out

# coping files
COPY exec/src/* .
COPY common/*.py ./common/

ENV LOGS=on
ENV IN=/data/in
ENV CONF=/data/conf
ENV BIN=/data/bin
ENV OUT=/data/out
ENV STD=/data/out

ENTRYPOINT ["python3", "-u", "main.py"]
