FROM alpine:3.21

WORKDIR /app

RUN apk update && apk add --no-cache build-base musl-dev libffi-dev python3 py3-pip
RUN pip install --break-system-packages pyinstaller 

RUN addgroup -S compgroup
RUN adduser -S compuser -G compgroup
RUN chown -R compuser:compgroup /app
USER compuser


COPY comp.sh .
RUN mkdir /tmp/out
RUN mkdir /tmp/in

ENV IN=/data/in
ENV OUT=/data/out

ENTRYPOINT ["./comp.sh"]
