FROM alipne:3.20

WORKDIR /app

RUN apk update && apk add --no-cache build-base musl-dev libffi-dev
RUN pip install pyinstaller 

RUN addgroup -S compgroup
RUN adduser -S compuser -G compgroup
USER compuser

COPY comp.sh .
RUN chmod +x comp.sh
RUN mkdir /tmp/out
RUN mkdir /tmp/in

ENV INPUT=/data/in
ENV OUTPUT=/data/out

ENTRYPOINT ["./comp.sh"]
