FROM alpine:3.20

RUN apk add --no-cache build-base

RUN addgroup -S compgroup
RUN adduser -S compuser -G compgroup
USER compuser

WORKDIR /app
COPY comp.sh .

RUN mkdir /tmp/src
RUN mkdir /tmp/out
RUN mkdir /tmp/bin

ENV SRC=/data/in
ENV OUT=/data/out
ENV BIN=/data/out


ENTRYPOINT ["./comp.sh"]
