FROM alpine:3.20

RUN apk add --no-cache build-base

RUN addgroup -S compgroup
RUN adduser -S compuser -G compgroup
USER compuser

WORKDIR /app
COPY comp.sh .
RUN mkdir /tmp/out
RUN mkdir /tmp/in

ENV INPUT=/data/in
ENV OUTPUT=/data/out


ENTRYPOINT ["./comp.sh"]
