FROM alpine

WORKDIR /app

COPY worker.py .

RUN apk add --no-cache python3 py3-docker-py
#RUN pip install docker

RUN mkdir -p "/data/comp-in" 
RUN mkdir -p "/data/comp-out"

RUN mkdir -p "/data/exec-in"
RUN mkdir -p "/data/exec-out" 

ENTRYPOINT [ "python3", "worker.py" ]

#docker build -t master ./src/master-worker
#docker run --rm --name "master-container" master