FROM docker:dind

RUN apk add --no-cache python3
RUN addgroup -S workergroup
RUN adduser -S workeruser -G workergroup

WORKDIR /app
COPY worker.py .

ENTRYPOINT ["python3", "-u", "worker.py"]

#docker build -t worker ./src/worker
#docker run --rm --privileged -v "/var/run/docker.sock:/var/run/docker.sock" --name worker worker 
