FROM alpine:latest

WORKDIR /app
COPY exec.sh .
RUN apk add --no-cache util-linux
RUN apk add --no-cache python3

ENTRYPOINT ["./exec.sh"]

# docker build -t exec .\containers\exec\
# docker run --rm -v "$(pwd)/containers/example/exec-in:/data/in:ro" -v "$(pwd)/containers/example/exec-out:/data/out" exec
