FROM alpine:3.21

WORKDIR /app


RUN apk add --no-cache python3 py3-pydantic
RUN addgroup -S execgroup
RUN adduser -S execuser -G execgroup

USER execuser

RUN mkdir /tmp/in
RUN mkdir /tmp/out

# coping files
COPY judge/src/* .
COPY common/*.py ./common/

ENV LOGS=on
ENV IN=/data/in
ENV ANS=/data/answer
ENV OUT=/data/out
ENV CONF=/data/conf

ENTRYPOINT ["python3", "-u", "main.py"]
