FROM alpine

RUN apk add --no-cache python3

RUN addgroup -S execgroup
RUN adduser -S execuser -G execgroup
RUN chown execuser .
USER execuser

WORKDIR /app
COPY exec.py .
COPY main.py .
COPY judge.py .
RUN mkdir /tmp/out
RUN mkdir /tmp/in


ENTRYPOINT ["python3", "-u", "main.py"]
