FROM alpine:3.21

WORKDIR /app

ARG LOGS=on

RUN apk add --no-cache python3
RUN addgroup -S execgroup
RUN adduser -S execuser -G execgroup

USER execuser

RUN mkdir /tmp/in
RUN mkdir /tmp/out

COPY exec.py .
COPY main.py .

ENV LOGS=$LOGS
ENV IN=/data/in
ENV BIN=/data/bin
ENV OUT=/data/out
ENV STD=/data/out

ENTRYPOINT ["python3", "-u", "main.py"]
