name: Build_and_Publish_image_to_DockerHub
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image for python compiler
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/compilers/python-compiler
          file: ./src/compilers/python-compiler/dockerfile
          tags: maciejrac/stos_pg:pythonCompiler-latest

      - name: Build and Push the Docker image for cpp compiler
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/compilers/cpp-compiler
          file: ./src/compilers/cpp-compiler/dockerfile
          tags: maciejrac/stos_pg:cppCompiler-latest

      - name: Build and Push the Docker image for Python exec
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/exec-python
          file: ./src/exec-python/dockerfile
          tags: maciejrac/stos_pg:pythonExec-latest

      - name: Build and Push the Docker image for Judge
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./src/judge
          file: ./src/judge/dockerfile
          tags: maciejrac/stos_pg:judge-latest